### ISSUE TITLE
s6 usage

### ISSUE THREAD

**Issue by olegstepura** [jcbiellikltd/docker-samba-server#1]
Hi!

Great work! Just wanted to share my notice that s6 usage here is doubtful, seems like you just start one background service (`nmbd` with `&`) and one foreground (`smbd`), which is primary and docker may control itself if the service is still alive (e.g. current `run.s6` may be just a shell script).

To make s6 usage as it was designed it looks like a separate `nmbd` service file should be created.

Just wanted to share my notices, please don't hesitate to respond if I'm right or wrong, I'm not an s6 expert ;)
Thanks!

**Comment by JoeBiellik** [comment]
Sorry for my slow reply but you are right, the two processes should be separate s6 services. I'll happily accept a patch, otherwise, I'll make the changes myself.

**Comment by olegstepura** [comment]
Hi! I'm on my way to rewrite it to place different services as separate s6 instances and make some other improvements (e.g. use `ADD` to download latest version of `s6-overlay`).
Will test my stuff and can make a PR afterwards
